In [2]:
import pandas as pd

In [3]:
my_df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')

my_df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [11]:
my_df = my_df.head(50)
my_df["quantity"] = my_df["quantity"].apply(lambda x: f"NO. {x}")
my_df

,order_id,quantity,item_name,choice_description,item_price
0,1,NO. NO. 1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,NO. NO. 1,Izze,[Clementine],$3.39
2,1,NO. NO. 1,Nantucket Nectar,[Apple],$3.39
3,1,NO. NO. 1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,NO. NO. 2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,NO. NO. 1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,NO. NO. 1,Side of Chips,NaN,$1.69
7,4,NO. NO. 1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,NO. NO. 1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,NO. NO. 1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,NO. NO. 1,Chips and Guacamole,NaN,$4.45
11,6,NO. NO. 1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,NO. NO. 1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,NO. NO. 1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,NO. NO. 1,Chips and Guacamole,NaN,$4.45
15,8,NO. NO. 1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,NO. NO. 1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,NO. NO. 1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,NO. NO. 2,Canned Soda,[Sprite],$2.18
19,10,NO. NO. 1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
20,10,NO. NO. 1,Chips and Guacamole,NaN,$4.45
21,11,NO. NO. 1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
22,11,NO. NO. 1,Nantucket Nectar,[Pomegranate Cherry],$3.39
23,12,NO. NO. 1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
24,12,NO. NO. 1,Izze,[Grapefruit],$3.39
25,13,NO. NO. 1,Chips and Fresh Tomato Salsa,NaN,$2.39
26,13,NO. NO. 1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
27,14,NO. NO. 1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
28,14,NO. NO. 1,Canned Soda,[Dr. Pepper],$1.09
29,15,NO. NO. 1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
30,15,NO. NO. 1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
31,16,NO. NO. 1,Steak Burrito,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$8.99
32,16,NO. NO. 1,Side of Chips,NaN,$1.69
33,17,NO. NO. 1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99
34,17,NO. NO. 1,Bottled Water,NaN,$1.09
35,18,NO. NO. 1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, Rice]",$8.75
36,18,NO. NO. 1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75
37,18,NO. NO. 1,Chips and Guacamole,NaN,$4.45
38,18,NO. NO. 1,Chips and Tomatillo Green Chili Salsa,NaN,$2.95
39,19,NO. NO. 1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75
40,19,NO. NO. 1,Chips,NaN,$2.15
41,20,NO. NO. 1,Chips and Guacamole,NaN,$4.45
42,20,NO. NO. 1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25
43,20,NO. NO. 1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$11.75
44,20,NO. NO. 1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75
45,21,NO. NO. 1,Chicken Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$10.98
46,21,NO. NO. 1,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...",$8.99
47,21,NO. NO. 1,Izze,[Blackberry],$3.39
48,22,NO. NO. 1,Steak Burrito,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99
49,22,NO. NO. 1,Chips and Guacamole,NaN,$3.99