In [2]:
import pandas as pd

In [3]:
my_df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')

my_df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [4]:
new_df = my_df.groupby("item_name")
new_df

In [5]:
new_df.count()

,order_id,quantity,choice_description,item_price
item_name,,,,
6 Pack Soft Drink,54,54,54,54
Barbacoa Bowl,66,66,66,66
Barbacoa Burrito,91,91,91,91
Barbacoa Crispy Tacos,11,11,11,11
Barbacoa Salad Bowl,10,10,10,10
Barbacoa Soft Tacos,25,25,25,25
Bottled Water,162,162,0,162
Bowl,2,2,2,2
Burrito,6,6,6,6
Canned Soda,104,104,104,104
Canned Soft Drink,301,301,301,301
Carnitas Bowl,68,68,68,68
Carnitas Burrito,59,59,59,59
Carnitas Crispy Tacos,7,7,7,7
Carnitas Salad,1,1,1,1
Carnitas Salad Bowl,6,6,6,6
Carnitas Soft Tacos,40,40,40,40
Chicken Bowl,726,726,726,726
Chicken Burrito,553,553,553,553
Chicken Crispy Tacos,47,47,47,47
Chicken Salad,9,9,9,9
Chicken Salad Bowl,110,110,110,110
Chicken Soft Tacos,115,115,115,115
Chips,211,211,0,211
Chips and Fresh Tomato Salsa,110,110,0,110
Chips and Guacamole,479,479,0,479
Chips and Mild Fresh Tomato Salsa,1,1,0,1
Chips and Roasted Chili Corn Salsa,22,22,0,22
Chips and Roasted Chili-Corn Salsa,18,18,0,18
Chips and Tomatillo Green Chili Salsa,43,43,0,43
Chips and Tomatillo Red Chili Salsa,48,48,0,48
Chips and Tomatillo-Green Chili Salsa,31,31,0,31
Chips and Tomatillo-Red Chili Salsa,20,20,0,20
Crispy Tacos,2,2,2,2
Izze,20,20,20,20
Nantucket Nectar,27,27,27,27
Salad,2,2,2,2
Side of Chips,101,101,0,101
Steak Bowl,211,211,211,211
Steak Burrito,368,368,368,368
Steak Crispy Tacos,35,35,35,35
Steak Salad,4,4,4,4
Steak Salad Bowl,29,29,29,29
Steak Soft Tacos,55,55,55,55
Veggie Bowl,85,85,85,85
Veggie Burrito,95,95,95,95
Veggie Crispy Tacos,1,1,1,1
Veggie Salad,6,6,6,6
Veggie Salad Bowl,18,18,18,18
Veggie Soft Tacos,7,7,7,7

In [6]:
new_df.min()

,order_id,quantity,choice_description,item_price
item_name,,,,
6 Pack Soft Drink,129,1,[Coke],$12.98
Barbacoa Bowl,19,1,"[Fresh Tomato (Mild), [Lettuce, Black Beans, R...",$11.48
Barbacoa Burrito,11,1,"[Fresh Tomato (Mild), [Black Beans, Rice, Sour...",$11.08
Barbacoa Crispy Tacos,75,1,"[Fresh Tomato Salsa, Guacamole]",$11.48
Barbacoa Salad Bowl,501,1,"[Fresh Tomato Salsa, Guacamole]",$11.89
Barbacoa Soft Tacos,26,1,"[Fresh Tomato Salsa, [Black Beans, Cheese, Let...",$11.48
Bottled Water,17,1,NaN,$1.09
Bowl,193,1,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$22.20
Burrito,214,1,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",$7.40
Canned Soda,9,1,[Coca Cola],$1.09
Canned Soft Drink,114,1,[Coke],$1.25
Carnitas Bowl,17,1,"[Fresh Tomato (Mild), [Guacamole, Lettuce, Ric...",$11.08
Carnitas Burrito,14,1,"[Fresh Tomato (Mild), [Lettuce, Black Beans, G...",$11.08
Carnitas Crispy Tacos,230,1,"[Fresh Tomato Salsa (Mild), [Cheese, Lettuce]]",$11.75
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99
Carnitas Salad Bowl,468,1,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.89
Carnitas Soft Tacos,103,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$11.75
Chicken Bowl,2,1,"[Fresh Tomato (Mild), [Guacamole, Rice]]",$10.58
Chicken Burrito,8,1,"[Fresh Tomato (Mild), [Black Beans, Rice, Sour...",$10.58
Chicken Crispy Tacos,6,1,"[Fresh Tomato Salsa (Mild), Fajita Veggies]",$10.98
Chicken Salad,109,1,"[Fresh Tomato Salsa (Mild), Black Beans]",$10.98
Chicken Salad Bowl,20,1,"[Fresh Tomato Salsa, Fajita Vegetables]",$11.25
Chicken Soft Tacos,6,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$10.98
Chips,19,1,NaN,$1.99
Chips and Fresh Tomato Salsa,1,1,NaN,$11.80
Chips and Guacamole,5,1,NaN,$13.35
Chips and Mild Fresh Tomato Salsa,279,1,NaN,$3.00
Chips and Roasted Chili Corn Salsa,102,1,NaN,$2.95
Chips and Roasted Chili-Corn Salsa,85,1,NaN,$2.39
Chips and Tomatillo Green Chili Salsa,18,1,NaN,$2.95
Chips and Tomatillo Red Chili Salsa,49,1,NaN,$2.95
Chips and Tomatillo-Green Chili Salsa,1,1,NaN,$2.39
Chips and Tomatillo-Red Chili Salsa,130,1,NaN,$2.39
Crispy Tacos,217,1,[Adobo-Marinated and Grilled Chicken],$7.40
Izze,1,1,[Blackberry],$3.39
Nantucket Nectar,1,1,[Apple],$3.39
Salad,575,1,"[Brown Rice, Adobo-Marinated and Grilled Chick...",$7.40
Side of Chips,3,1,NaN,$1.69
Steak Bowl,25,1,"[Fresh Tomato (Mild), [Guacamole, Lettuce, Pin...",$11.08
Steak Burrito,4,1,[Brown Rice],$11.08
Steak Crispy Tacos,40,1,"[Fresh Tomato (Mild), [Lettuce, Cheese]]",$11.75
Steak Salad,276,1,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$8.69
Steak Salad Bowl,123,1,"[Fresh Tomato Salsa, Lettuce]",$11.89
Steak Soft Tacos,4,1,"[Fresh Tomato Salsa (Mild), [Cheese, Sour Cream]]",$11.48
Veggie Bowl,28,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$10.98
Veggie Burrito,26,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Faji...",$10.98
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49
Veggie Salad,686,1,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49
Veggie Salad Bowl,83,1,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$11.25
Veggie Soft Tacos,304,1,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$11.25

In [7]:
new_df.max()

,order_id,quantity,choice_description,item_price
item_name,,,,
6 Pack Soft Drink,1803,2,[Sprite],$6.49
Barbacoa Bowl,1825,1,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",$9.25
Barbacoa Burrito,1827,1,"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomat...",$9.25
Barbacoa Crispy Tacos,1330,2,"[[Roasted Chili Corn Salsa (Medium), Tomatillo...",$9.25
Barbacoa Salad Bowl,1751,1,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",$9.39
Barbacoa Soft Tacos,1703,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$9.25
Bottled Water,1831,10,NaN,$7.50
Bowl,279,3,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$7.40
Burrito,313,1,"[White Rice, Adobo-Marinated and Grilled Steak...",$7.40
Canned Soda,1621,4,[Sprite],$4.36
Canned Soft Drink,1829,4,[Sprite],$5.00
Carnitas Bowl,1831,3,"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomat...",$9.25
Carnitas Burrito,1821,2,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$9.25
Carnitas Crispy Tacos,1774,2,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$9.25
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99
Carnitas Salad Bowl,1692,1,"[Tomatillo Green Chili Salsa, [Rice, Pinto Bea...",$9.39
Carnitas Soft Tacos,1811,1,"[Tomatillo-Red Chili Salsa (Hot), [Cheese, Sou...",$9.25
Chicken Bowl,1828,3,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",$8.75
Chicken Burrito,1817,4,"[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...",$8.75
Chicken Crispy Tacos,1775,2,"[Tomatillo-Green Chili Salsa (Medium), [Black ...",$8.75
Chicken Salad,1598,1,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.49
Chicken Salad Bowl,1834,2,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$8.75
Chicken Soft Tacos,1832,2,"[[Tomatillo-Red Chili Salsa (Hot), Roasted Chi...",$8.75
Chips,1831,3,NaN,$6.45
Chips and Fresh Tomato Salsa,1790,15,NaN,$5.90
Chips and Guacamole,1832,4,NaN,$8.90
Chips and Mild Fresh Tomato Salsa,279,1,NaN,$3.00
Chips and Roasted Chili Corn Salsa,1513,2,NaN,$5.90
Chips and Roasted Chili-Corn Salsa,1565,1,NaN,$2.39
Chips and Tomatillo Green Chili Salsa,1787,2,NaN,$5.90
Chips and Tomatillo Red Chili Salsa,1779,2,NaN,$5.90
Chips and Tomatillo-Green Chili Salsa,1604,2,NaN,$4.78
Chips and Tomatillo-Red Chili Salsa,1637,3,NaN,$7.17
Crispy Tacos,217,1,[Adobo-Marinated and Grilled Steak],$7.40
Izze,1468,1,[Grapefruit],$3.39
Nantucket Nectar,1632,2,[Pomegranate Cherry],$6.78
Salad,575,1,"[White Rice, Adobo-Marinated and Grilled Chick...",$7.40
Side of Chips,1629,8,NaN,$5.07
Steak Bowl,1796,3,"[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomat...",$9.25
Steak Burrito,1833,3,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$9.25
Steak Crispy Tacos,1810,2,"[[Roasted Chili Corn Salsa (Medium), Tomatillo...",$9.25
Steak Salad,1406,1,"[[Lettuce, Fajita Veggies]]",$8.99
Steak Salad Bowl,1818,2,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$9.39
Steak Soft Tacos,1808,2,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$9.25
Veggie Bowl,1780,2,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.75
Veggie Burrito,1830,3,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.75
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49
Veggie Salad,1635,1,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.49
Veggie Salad Bowl,1818,1,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
Veggie Soft Tacos,1559,2,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75

In [8]:
new_df.sum()

,order_id,quantity,choice_description,item_price
item_name,,,,
6 Pack Soft Drink,52322,55,[Sprite][Diet Coke][Coke][Diet Coke][Diet Coke...,$6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.4...
Barbacoa Bowl,53972,66,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75 $11.75 $9.25 $8.99 $9.25 $11.75 $9.25 $...
Barbacoa Burrito,74718,91,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99 $9.25 $9.25 $11.75 $11.75 $9.25 $8.99 $1...
Barbacoa Crispy Tacos,5613,12,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75 $9.25 $11.48 $11.75 $9.25 $9.25 $8.99 $...
Barbacoa Salad Bowl,9708,10,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$11.89 $11.89 $9.39 $9.39 $9.39 $11.89 $11.89 ...
Barbacoa Soft Tacos,18725,25,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$9.25 $9.25 $8.99 $9.25 $9.25 $11.75 $11.75 $9...
Bottled Water,175944,211,,$1.09 $1.09 $1.09 $1.50 $1.50 $1.50 $3.00 $1.5...
Bowl,472,4,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20 $7.40
Burrito,1550,6,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",$7.40 $7.40 $7.40 $7.40 $7.40 $7.40
Canned Soda,76396,126,[Sprite][Dr. Pepper][Mountain Dew][Sprite][Dr....,$2.18 $1.09 $2.18 $1.09 $1.09 $1.09 $1.09 $2.1...
Canned Soft Drink,304753,351,[Coke][Sprite][Coke][Coke][Lemonade][Sprite][D...,$1.25 $1.25 $1.25 $1.25 $1.25 $1.25 $1.25 $1.2...
Carnitas Bowl,62742,71,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99 $11.75 $9.25 $11.48 $8.99 $8.99 $23.50 $...
Carnitas Burrito,51652,60,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99 $9.25 $11.75 $9.25 $9.25 $9.25 $11.75 $9...
Carnitas Crispy Tacos,5868,8,[Roasted Chili Corn Salsa][Tomatillo Green Chi...,$9.25 $11.75 $8.99 $11.75 $8.99 $17.98 $9.25
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99
Carnitas Salad Bowl,6693,6,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.89 $9.39 $11.89 $9.39 $11.89 $11.89
Carnitas Soft Tacos,37673,40,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$9.25 $9.25 $9.25 $9.25 $9.25 $8.99 $8.99 $8.9...
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...
Chicken Burrito,497303,591,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49 $8.49 $10.98 $8.49 $10.98 $10.98 $8.75 $...
Chicken Crispy Tacos,47382,50,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75 $17.50 $11.25 $8.49 $8.49 $11.25 $8.75 $...
Chicken Salad,10465,9,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$10.98 $10.98 $8.49 $8.49 $8.49 $8.49 $8.49 $8...
Chicken Salad Bowl,117104,123,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75 $22.50 $22.50 $8.75 $17.50 $8.75 $8.75 $...
Chicken Soft Tacos,98395,120,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75 $8.75 $8.75 $8.75 $11.25 $8.49 $8.49 $8....
Chips,208004,230,,$2.15 $2.15 $2.15 $2.15 $2.15 $2.15 $4.30 $2.1...
Chips and Fresh Tomato Salsa,100419,130,,$2.39 $2.39 $2.39 $2.95 $2.95 $2.95 $2.95 $2.3...
Chips and Guacamole,449959,506,,$4.45 $4.45 $4.45 $4.45 $4.45 $3.99 $4.45 $3.9...
Chips and Mild Fresh Tomato Salsa,279,1,,$3.00
Chips and Roasted Chili Corn Salsa,14999,23,,$2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.9...
Chips and Roasted Chili-Corn Salsa,17462,18,,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Chips and Tomatillo Green Chili Salsa,41170,45,,$2.95 $2.95 $5.90 $2.95 $2.95 $2.95 $2.95 $2.9...
Chips and Tomatillo Red Chili Salsa,45556,50,,$2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.9...
Chips and Tomatillo-Green Chili Salsa,21826,33,,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Chips and Tomatillo-Red Chili Salsa,18344,25,,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Crispy Tacos,434,2,[Adobo-Marinated and Grilled Steak][Adobo-Mari...,$7.40 $7.40
Izze,10587,20,[Clementine][Grapefruit][Blackberry][Blackberr...,$3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $3.3...
Nantucket Nectar,21814,29,[Apple][Pomegranate Cherry][Pineapple Orange B...,$3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $6.78 $3.3...
Salad,1150,2,"[Brown Rice, Adobo-Marinated and Grilled Chick...",$7.40 $7.40
Side of Chips,84769,110,,$1.69 $1.69 $1.69 $1.69 $1.69 $1.69 $1.69 $1.6...
Steak Bowl,193752,221,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.99 $8.99 $11.75 $11.75 $8.99 $11.48 $9.25 $...
Steak Burrito,328437,386,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75 $9.25 $8.99 $11.75 $8.99 $8.99 $8.99 $8...
Steak Crispy Tacos,35818,36,"[Fresh Tomato Salsa, Sour Cream][[Roasted Chil...",$9.25 $8.99 $9.25 $8.69 $8.99 $9.25 $8.99 $9.2...
Steak Salad,2362,4,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99 $8.99 $8.99 $8.69
Steak Salad Bowl,29590,31,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",$23.78 $11.89 $9.39 $23.78 $11.89 $11.89 $11.8...
Steak Soft Tacos,50177,56,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25 $9.25 $8.99 $9.25 $8.99 $8.99 $9.25 $9.2...
Veggie Bowl,72270,87,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25 $8.49 $11.25 $11.25 $8.49 $11.25 $11.25...
Veggie Burrito,80962,97,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25 $8.49 $11.25 $11.25 $10.98 $8.49 $8.49 ...
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49
Veggie Salad,7265,6,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.49 $8.49 $8.49 $8.49 $8.49 $8.49
Veggie Salad Bowl,17303,18,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25 $11.25 $11.25 $11.25 $8.75 $8.75 $11.25...
Veggie Soft Tacos,5520,8,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25 $8.75 $8.49 $11.25 $8.75 $8.49 $16.98

In [10]:
new_df.describe()

                                      order_id                           \
                                         count         mean         std
item_name
6 Pack Soft Drink                         54.0   968.925926  537.830402
Barbacoa Bowl                             66.0   817.757576  538.969246
Barbacoa Burrito                          91.0   821.076923  555.170029
Barbacoa Crispy Tacos                     11.0   510.272727  421.439934
Barbacoa Salad Bowl                       10.0   970.800000  450.374363
Barbacoa Soft Tacos                       25.0   749.000000  465.655094
Bottled Water                            162.0  1086.074074  488.464390
Bowl                                       2.0   236.000000   60.811183
Burrito                                    6.0   258.333333   49.078169
Canned Soda                              104.0   734.576923  534.727400
Canned Soft Drink                        301.0  1012.468439  544.687106
Carnitas Bowl                             68.0   922.676471  509.253315
Carnitas Burrito                          59.0   875.457627  556.825743
Carnitas Crispy Tacos                      7.0   838.285714  592.813269
Carnitas Salad                             1.0  1500.000000         NaN
Carnitas Salad Bowl                        6.0  1115.500000  458.401025
Carnitas Soft Tacos                       40.0   941.825000  504.494207
Chicken Bowl                             726.0   983.369146  503.756650
Chicken Burrito                          553.0   899.282098  528.027208
Chicken Crispy Tacos                      47.0  1008.127660  500.469763
Chicken Salad                              9.0  1162.777778  531.935094
Chicken Salad Bowl                       110.0  1064.581818  527.530831
Chicken Soft Tacos                       115.0   855.608696  515.408213
Chips                                    211.0   985.800948  520.863247
Chips and Fresh Tomato Salsa             110.0   912.900000  520.915354
Chips and Guacamole                      479.0   939.371608  552.857597
Chips and Mild Fresh Tomato Salsa          1.0   279.000000         NaN
Chips and Roasted Chili Corn Salsa        22.0   681.772727  363.929079
Chips and Roasted Chili-Corn Salsa        18.0   970.111111  418.975205
Chips and Tomatillo Green Chili Salsa     43.0   957.441860  585.679146
Chips and Tomatillo Red Chili Salsa       48.0   949.083333  480.451022
Chips and Tomatillo-Green Chili Salsa     31.0   704.064516  577.815711
Chips and Tomatillo-Red Chili Salsa       20.0   917.200000  473.610722
Crispy Tacos                               2.0   217.000000    0.000000
Izze                                      20.0   529.350000  452.844492
Nantucket Nectar                          27.0   807.925926  530.078436
Salad                                      2.0   575.000000    0.000000
Side of Chips                            101.0   839.297030  476.118925
Steak Bowl                               211.0   918.255924  500.217106
Steak Burrito                            368.0   892.491848  538.512954
Steak Crispy Tacos                        35.0  1023.371429  501.807972
Steak Salad                                4.0   590.500000  545.017737
Steak Salad Bowl                          29.0  1020.344828  540.599817
Steak Soft Tacos                          55.0   912.309091  614.537793
Veggie Bowl                               85.0   850.235294  527.307303
Veggie Burrito                            95.0   852.231579  520.757293
Veggie Crispy Tacos                        1.0   668.000000         NaN
Veggie Salad                               6.0  1210.833333  318.122880
Veggie Salad Bowl                         18.0   961.277778  613.598240
Veggie Soft Tacos                          7.0   788.571429  456.184852

                                                                         \
                                          min      25%     50%      75%
item_name
6 Pack Soft Drink                       129.0   488.50   922.0  1473.50
Barbacoa Bowl                            19.0   428.75   690.5  1259.25
Barbacoa Burrito                         11.0   302.50   748.0  1286.50
Barbacoa Crispy Tacos                    75.0   195.50   343.0   762.00
Barbacoa Salad Bowl                     501.0   576.00   854.0  1330.25
Barbacoa Soft Tacos                      26.0   467.00   675.0   966.00
Bottled Water                            17.0   753.00  1082.0  1513.00
Bowl                                    193.0   214.50   236.0   257.50
Burrito                                 214.0   214.75   248.0   304.50
Canned Soda                               9.0   186.00   701.0  1205.75
Canned Soft Drink                       114.0   546.00   989.0  1563.00
Carnitas Bowl                            17.0   548.75   928.0  1205.00
Carnitas Burrito                         14.0   397.00   844.0  1377.50
Carnitas Crispy Tacos                   230.0   451.50   658.0  1151.50
Carnitas Salad                         1500.0  1500.00  1500.0  1500.00
Carnitas Salad Bowl                     468.0   825.75  1139.0  1435.00
Carnitas Soft Tacos                     103.0   578.50   897.0  1367.25
Chicken Bowl                              2.0   599.50   974.5  1411.00
Chicken Burrito                           8.0   462.00   895.0  1378.00
Chicken Crispy Tacos                      6.0   486.00  1156.0  1342.00
Chicken Salad                           109.0  1181.00  1349.0  1491.00
Chicken Salad Bowl                       20.0   650.25  1160.0  1508.50
Chicken Soft Tacos                        6.0   430.50   824.0  1242.00
Chips                                    19.0   607.00   952.0  1448.00
Chips and Fresh Tomato Salsa              1.0   502.00   931.0  1370.00
Chips and Guacamole                       5.0   457.50   949.0  1444.00
Chips and Mild Fresh Tomato Salsa       279.0   279.00   279.0   279.00
Chips and Roasted Chili Corn Salsa      102.0   448.75   609.5   899.25
Chips and Roasted Chili-Corn Salsa       85.0   698.75  1050.0  1280.75
Chips and Tomatillo Green Chili Salsa    18.0   428.50   922.0  1490.00
Chips and Tomatillo Red Chili Salsa      49.0   669.00   873.0  1334.25
Chips and Tomatillo-Green Chili Salsa     1.0   103.00   513.0  1292.00
Chips and Tomatillo-Red Chili Salsa     130.0   589.25   910.5  1318.50
Crispy Tacos                            217.0   217.00   217.0   217.00
Izze                                      1.0   155.00   465.5   891.50
Nantucket Nectar                          1.0   314.00   947.0  1152.50
Salad                                   575.0   575.00   575.0   575.00
Side of Chips                             3.0   424.00   895.0  1238.00
Steak Bowl                               25.0   503.50   915.0  1305.00
Steak Burrito                             4.0   413.75   891.0  1366.00
Steak Crispy Tacos                       40.0   565.50  1129.0  1425.50
Steak Salad                             276.0   302.25   340.0   628.25
Steak Salad Bowl                        123.0   612.00  1042.0  1403.00
Steak Soft Tacos                          4.0   220.50   973.0  1483.00
Veggie Bowl                              28.0   367.00   818.0  1255.00
Veggie Burrito                           26.0   364.50   801.0  1303.00
Veggie Crispy Tacos                     668.0   668.00   668.0   668.00
Veggie Salad                            686.0  1118.50  1227.5  1362.00
Veggie Salad Bowl                        83.0   429.50   904.5  1564.75
Veggie Soft Tacos                       304.0   444.50   688.0  1040.00

                                              quantity                      \
                                          max    count      mean       std
item_name
6 Pack Soft Drink                      1803.0     54.0  1.018519  0.136083
Barbacoa Bowl                          1825.0     66.0  1.000000  0.000000
Barbacoa Burrito                       1827.0     91.0  1.000000  0.000000
Barbacoa Crispy Tacos                  1330.0     11.0  1.090909  0.301511
Barbacoa Salad Bowl                    1751.0     10.0  1.000000  0.000000
Barbacoa Soft Tacos                    1703.0     25.0  1.000000  0.000000
Bottled Water                          1831.0    162.0  1.302469  1.034135
Bowl                                    279.0      2.0  2.000000  1.414214
Burrito                                 313.0      6.0  1.000000  0.000000
Canned Soda                            1621.0    104.0  1.211538  0.476090
Canned Soft Drink                      1829.0    301.0  1.166113  0.495629
Carnitas Bowl                          1831.0     68.0  1.044118  0.269539
Carnitas Burrito                       1821.0     59.0  1.016949  0.130189
Carnitas Crispy Tacos                  1774.0      7.0  1.142857  0.377964
Carnitas Salad                         1500.0      1.0  1.000000       NaN
Carnitas Salad Bowl                    1692.0      6.0  1.000000  0.000000
Carnitas Soft Tacos                    1811.0     40.0  1.000000  0.000000
Chicken Bowl                           1828.0    726.0  1.048209  0.226861
Chicken Burrito                        1817.0    553.0  1.068716  0.305116
Chicken Crispy Tacos                   1775.0     47.0  1.063830  0.247092
Chicken Salad                          1598.0      9.0  1.000000  0.000000
Chicken Salad Bowl                     1834.0    110.0  1.118182  0.324301
Chicken Soft Tacos                     1832.0    115.0  1.043478  0.204824
Chips                                  1831.0    211.0  1.090047  0.303072
Chips and Fresh Tomato Salsa           1790.0    110.0  1.181818  1.369268
Chips and Guacamole                    1832.0    479.0  1.056367  0.264647
Chips and Mild Fresh Tomato Salsa       279.0      1.0  1.000000       NaN
Chips and Roasted Chili Corn Salsa     1513.0     22.0  1.045455  0.213201
Chips and Roasted Chili-Corn Salsa     1565.0     18.0  1.000000  0.000000
Chips and Tomatillo Green Chili Salsa  1787.0     43.0  1.046512  0.213083
Chips and Tomatillo Red Chili Salsa    1779.0     48.0  1.041667  0.201941
Chips and Tomatillo-Green Chili Salsa  1604.0     31.0  1.064516  0.249731
Chips and Tomatillo-Red Chili Salsa    1637.0     20.0  1.250000  0.638666
Crispy Tacos                            217.0      2.0  1.000000  0.000000
Izze                                   1468.0     20.0  1.000000  0.000000
Nantucket Nectar                       1632.0     27.0  1.074074  0.266880
Salad                                   575.0      2.0  1.000000  0.000000
Side of Chips                          1629.0    101.0  1.089109  0.722482
Steak Bowl                             1796.0    211.0  1.047393  0.234278
Steak Burrito                          1833.0    368.0  1.048913  0.239889
Steak Crispy Tacos                     1810.0     35.0  1.028571  0.169031
Steak Salad                            1406.0      4.0  1.000000  0.000000
Steak Salad Bowl                       1818.0     29.0  1.068966  0.257881
Steak Soft Tacos                       1808.0     55.0  1.018182  0.134840
Veggie Bowl                            1780.0     85.0  1.023529  0.152477
Veggie Burrito                         1830.0     95.0  1.021053  0.205196
Veggie Crispy Tacos                     668.0      1.0  1.000000       NaN
Veggie Salad                           1635.0      6.0  1.000000  0.000000
Veggie Salad Bowl                      1818.0     18.0  1.000000  0.000000
Veggie Soft Tacos                      1559.0      7.0  1.142857  0.377964


                                       min  25%  50%  75%   max
item_name
6 Pack Soft Drink                      1.0  1.0  1.0  1.0   2.0
Barbacoa Bowl                          1.0  1.0  1.0  1.0   1.0
Barbacoa Burrito                       1.0  1.0  1.0  1.0   1.0
Barbacoa Crispy Tacos                  1.0  1.0  1.0  1.0   2.0
Barbacoa Salad Bowl                    1.0  1.0  1.0  1.0   1.0
Barbacoa Soft Tacos                    1.0  1.0  1.0  1.0   1.0
Bottled Water                          1.0  1.0  1.0  1.0  10.0
Bowl                                   1.0  1.5  2.0  2.5   3.0
Burrito                                1.0  1.0  1.0  1.0   1.0
Canned Soda                            1.0  1.0  1.0  1.0   4.0
Canned Soft Drink                      1.0  1.0  1.0  1.0   4.0
Carnitas Bowl                          1.0  1.0  1.0  1.0   3.0
Carnitas Burrito                       1.0  1.0  1.0  1.0   2.0
Carnitas Crispy Tacos                  1.0  1.0  1.0  1.0   2.0
Carnitas Salad                         1.0  1.0  1.0  1.0   1.0
Carnitas Salad Bowl                    1.0  1.0  1.0  1.0   1.0
Carnitas Soft Tacos                    1.0  1.0  1.0  1.0   1.0
Chicken Bowl                           1.0  1.0  1.0  1.0   3.0
Chicken Burrito                        1.0  1.0  1.0  1.0   4.0
Chicken Crispy Tacos                   1.0  1.0  1.0  1.0   2.0
Chicken Salad                          1.0  1.0  1.0  1.0   1.0
Chicken Salad Bowl                     1.0  1.0  1.0  1.0   2.0
Chicken Soft Tacos                     1.0  1.0  1.0  1.0   2.0
Chips                                  1.0  1.0  1.0  1.0   3.0
Chips and Fresh Tomato Salsa           1.0  1.0  1.0  1.0  15.0
Chips and Guacamole                    1.0  1.0  1.0  1.0   4.0
Chips and Mild Fresh Tomato Salsa      1.0  1.0  1.0  1.0   1.0
Chips and Roasted Chili Corn Salsa     1.0  1.0  1.0  1.0   2.0
Chips and Roasted Chili-Corn Salsa     1.0  1.0  1.0  1.0   1.0
Chips and Tomatillo Green Chili Salsa  1.0  1.0  1.0  1.0   2.0
Chips and Tomatillo Red Chili Salsa    1.0  1.0  1.0  1.0   2.0
Chips and Tomatillo-Green Chili Salsa  1.0  1.0  1.0  1.0   2.0
Chips and Tomatillo-Red Chili Salsa    1.0  1.0  1.0  1.0   3.0
Crispy Tacos                           1.0  1.0  1.0  1.0   1.0
Izze                                   1.0  1.0  1.0  1.0   1.0
Nantucket Nectar                       1.0  1.0  1.0  1.0   2.0
Salad                                  1.0  1.0  1.0  1.0   1.0
Side of Chips                          1.0  1.0  1.0  1.0   8.0
Steak Bowl                             1.0  1.0  1.0  1.0   3.0
Steak Burrito                          1.0  1.0  1.0  1.0   3.0
Steak Crispy Tacos                     1.0  1.0  1.0  1.0   2.0
Steak Salad                            1.0  1.0  1.0  1.0   1.0
Steak Salad Bowl                       1.0  1.0  1.0  1.0   2.0
Steak Soft Tacos                       1.0  1.0  1.0  1.0   2.0
Veggie Bowl                            1.0  1.0  1.0  1.0   2.0
Veggie Burrito                         1.0  1.0  1.0  1.0   3.0
Veggie Crispy Tacos                    1.0  1.0  1.0  1.0   1.0
Veggie Salad                           1.0  1.0  1.0  1.0   1.0
Veggie Salad Bowl                      1.0  1.0  1.0  1.0   1.0
Veggie Soft Tacos                      1.0  1.0  1.0  1.0   2.0